# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid-generator}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["guillaume belleguic"]
  s.date = %q{2010-04-02}
  s.description = %q{Mongoid orm generator for rails 3}
  s.email = %q{guillaume.belleguic@cixi.eu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/mongoid.rb",
     "lib/generators/mongoid/model/model_generator.rb",
     "lib/generators/mongoid/model/templates/model.rb",
     "lib/mongoid-generator.rb",
     "mongoid-generator.gemspec",
     "test/helper.rb",
     "test/test_mongoid-generator.rb"
  ]
  s.homepage = %q{http://github.com/tetsuo692/mongoid-generator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mongoid orm generator}
  s.test_files = [
    "test/helper.rb",
     "test/test_mongoid-generator.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

